Added support for self-exit thread.
device-automation-bus/dab-adapter-rs pull request #3
Opened 2023-08-02 18:01 UTC by arun-madhavan-013

This change brings a file monitoring thread to control the binary runtime based on a file status.
A systemd path service can start this dab bridge on device but it will not be able to stop it when the file status changes.
The new thread will monitor for existence of /run/dab-enable file and if it gets deleted bridge will self-exit.

2023-08-02 18:13 UTC, bgy36ww requested changes

2023-08-02 18:13 UTC, bgy36ww commented on src/adapter.rs
> +        let handler = thread::Builder::new().name("ExitPathMonitor".to_string()).spawn(move || { fd_monitor_thread(); });
Unused variable.

2023-08-03 18:40 UTC, bgy36ww approved these changes

2023-08-04 11:09 UTC, denisyuji approved these changes

2023-08-04 11:09 UTC, merged